disabled_rules:
  - opening_brace
  - todo
#  - variable_name #doesn't allow underscores
  - unused_optional_binding #doesn't allow try? binding
  - switch_case_alignment
  - fallthrough
  - identifier_name
  - vertical_parameter_alignment
  - trailing_comma
opt_in_rules:
  - line_length
  - attributes
  - closure_spacing
  - explicit_init
  - first_where
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - object_literal
  - trailing_comma
#  - valid_docs
    
excluded:
  - Carthage
  - vendor
#variable_name:
#  excluded:
#    - id
#    - db
#    - at
function_body_length:
  warning: 60
file_length:
  warning: 900
line_length:
  warning: 300
  error: 500
  ignores_comments: true
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
large_tuple:
  warning: 4
  error: 4
number_separator:
  minimum_length: 5
type_body_length:
  warning: 400
attributes:
  always_on_same_line:
    - "@IBAction"
    - "@NSManaged"
    - "@objc"
# following doesn't work, but should
#identifier_name:
#  - min_length: 2

