disabled_rules:
  - opening_brace
  - line_length
  - todo
  - variable_name #doesn't allow underscores
opt_in_rules:

excluded:
  - Carthage
  - vendor
variable_name:
  excluded:
    - id
file_length:
  warning: 450
trailing_whitespace:
  ignores_empty_lines: true
large_tuple:
  warning: 4
  error: 4
